### ISSUE TITLE
Request error when enable telegraph with socks proxy

### ISSUE THREAD

**Issue by Green-m** [indes/flowerss-bot#19]
`docker-compose logs` I got this error info:

```
2019/11/25 04:09:01 Telegraph Enabled, Token len:  3 Token:  [<redacted> <redacted>  <redacted> ]
service.flowerss_1     | 2019/11/25 04:09:02 request error: Post https://api.telegra.ph/getAccountInfo: x509: certificate is valid for atlassolutions.com, atdmt.com, xx.atlassbx.com, *.atdmt2.com, *.atlassolutions.com, *.atdmt.com, *.xx.atlassbx.com, atdmt2.com, *.atlassbx.com, atlassbx.com, not api.telegra.ph
service.flowerss_1     | 2019/11/25 04:09:02 Telegraph load error: Post https://api.telegra.ph/getAccountInfo: x509: certificate is valid for atlassolutions.com, atdmt.com, xx.atlassbx.com, *.atdmt2.com, *.atlassolutions.com, *.atdmt.com, *.xx.atlassbx.com, atdmt2.com, *.atlassbx.com, atlassbx.com, not api.telegra.ph token: <redacted> 
service.flowerss_1     | 2019/11/25 04:09:03 request error: Post https://api.telegra.ph/getAccountInfo: x509: certificate is valid for atlassolutions.com, atdmt.com, xx.atlassbx.com, *.atdmt2.com, *.atlassolutions.com, *.atdmt.com, *.xx.atlassbx.com, atdmt2.com, *.atlassbx.com, atlassbx.com, not api.telegra.ph
service.flowerss_1     | 2019/11/25 04:09:03 Telegraph load error: Post https://api.telegra.ph/getAccountInfo: x509: certificate is valid for atlassolutions.com, atdmt.com, xx.atlassbx.com, *.atdmt2.com, *.atlassolutions.com, *.atdmt.com, *.xx.atlassbx.com, atdmt2.com, *.atlassbx.com, atlassbx.com, not api.telegra.ph token: <redacted> 
service.flowerss_1     | 2019/11/25 04:09:05 request error: Post https://api.telegra.ph/getAccountInfo: x509: certificate is valid for atlassolutions.com, atdmt.com, xx.atlassbx.com, *.atdmt2.com, *.atlassolutions.com, *.atdmt.com, *.xx.atlassbx.com, atdmt2.com, *.atlassbx.com, atlassbx.com, not api.telegra.ph
service.flowerss_1     | 2019/11/25 04:09:05 Telegraph load error: Post https://api.telegra.ph/getAccountInfo: x509: certificate is valid for atlassolutions.com, atdmt.com, xx.atlassbx.com, *.atdmt2.com, *.atlassolutions.com, *.atdmt.com, *.xx.atlassbx.com, atdmt2.com, *.atlassbx.com, atlassbx.com, not api.telegra.ph token: <redacted> 
service.flowerss_1     | 2019/11/25 04:09:05 Telegraph token error, telegraph disabled
service.flowerss_1     | 2019/11/25 04:09:05 Bot Token: <redacted> Proxy: 192.168.6.77:1080
service.flowerss_1     | 2019/11/25 04:09:09 Source Title: <paper - Last paper> Subscriber: 1 New Contents: 0
root@green-nas:/d2_data/rsshub# curl https://api.telegra.ph/getAccountInfo --proxy socks5://192.168.6.77:1080
```

my config.yml
```
root@green-nas:/d2_data/rsshub# cat flowerss/config.yml
bot_token: <redacted> 
telegraph_token:
  - <redacted> 
  - <redacted> 
  - <redacted> 
preview_text: 0
update_interval: 10
error_threshold: 100
socks5: 192.168.6.77:1080

sqlite:
  path: ./data.db
```

My proxy worked well with `curl`:
```
root@green-nas:/d2_data/rsshub# curl https://api.telegra.ph/getAccountInfo --proxy socks5://192.168.6.77:1080
{"ok":false,"error":"ACCESS_TOKEN_INVALID"}root@green-nas:/d2_data/rsshub# ls
```

And I install it with docker-compose, here is config:
```
version: '3'

services:
  service.flowerss:
    image: indes/flowerss-bot:latest
    #environment:
    #  HTTP_PROXY: http://192.168.6.77:8000
    #  HTTPS_PROXY: http://192.168.6.77:8000
    volumes:
      - ./flowerss:/flowerss
    working_dir: /flowerss
    links:
      - "service.rsshub:rsshub"
    logging:
      options:
                #driver: "json-file"
        max-size: '500k'
    restart: always

  service.rsshub:
    image: diygod/rsshub
    restart: always
    ports:
      - "1200:1200"
    environment:
      HTTP_PROXY: http://192.168.6.77:8000
      HTTPS_PROXY: http://192.168.6.77:8000
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://db.redis:6379/'
      PUPPETEER_WS_ENDPOINT: 'ws://service.browserless:3000'
    depends_on:
      - db.redis
      - service.browserless

  service.browserless:
    image: browserless/chrome
    restart: always

  db.redis:
    image: redis
    restart: always
    volumes:
        - redis-data:/data

volumes:
  redis-data:
```

Feel free to ask me to provide more info if you need, thank you in advance.
